version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    networks:
    - productnetwork
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
   
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD : "AaBbCcD123!"
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "AaBbCcD123!"
    ports:
     - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
     - ./init.sql:/init.sql
    networks:
     - productnetwork
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "AaBbCcD123!", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  order-service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=OrderDb;User Id=sa;Password=AaBbCcD123!;TrustServerCertificate=True;
    ports: 
      - "3001:80"
      - "3031:443"
    networks:
     - productnetwork
    restart: on-failure:5 
    depends_on:
      rabbitmq:
        condition: service_healthy
        
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: data123!#
      MYSQL_DATABASE: PaymentDb
      MYSQL_USER: paymentuser
      MYSQL_PASSWORD: paymentpass
    ports:
      - "3307:3306"
    networks:
      - productnetwork
    volumes:
      - mysqlvolume:/var/lib/mysql
      - ./initDb/payment.sql:/docker-entrypoint-initdb.d/payment.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  payment-service:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=Server=localhost;Port=3306;Database=PaymentDb;User=root;Password=data123!#;
    ports: 
      - "3002:81"
      - "3032:444"
    networks:
     - productnetwork
    restart: on-failure:5 
    depends_on:
      rabbitmq:
        condition: service_healthy
      mysql:
        condition: service_healthy
        
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false  
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - productnetwork
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - productnetwork
    depends_on:
      elasticsearch:
        condition: service_healthy
        
networks:
  productnetwork:

volumes:
  sqlvolume:
  mysqlvolume:
