CREATE DATABASE OrderDb;
GO

USE OrderDb;
GO

CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    CustomerId INT NOT NULL,
    OrderDate DATETIME NOT NULL,
    OrderStatus INT NOT NULL,
    OrderAmount FLOAT NOT NULL
);
GO

CREATE TABLE OrderItem (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    ProductId INT NOT NULL,
    UnitPrice FLOAT NOT NULL,
    Units INT NOT NULL,
    OrderId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_OrderItems_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id) ON DELETE CASCADE
);
GO
